language: bash
services:
  - docker
script:
  - docker-compose build
after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      docker-compose push
    fi
