version: '3'
services:

  # Official

  php56-fpm-alpine-official:
    image: php:5.6-fpm-alpine
  php56-fpm-stretch-official:
    image: php:5.6-fpm-stretch
  php71-fpm-alpine-official:
    image: php:7.1-fpm-alpine
  php71-fpm-stretch-official:
    image: php:7.1-fpm-stretch
  php72-fpm-alpine-official:
    image: php:7.2-fpm-alpine
  php72-fpm-stretch-official:
    image: php:7.2-fpm-stretch

  # PHP 5.6

  # php56-fpm-alpine-base:
  #   build:
  #     context: ./5.6/alpine/fpm
  #     dockerfile: base.Dockerfile
  #   image: my127/magento1:5.6-fpm-alpine

  # php56-fpm-alpine-console:
  #   build:
  #     context: ./5.6/alpine/fpm
  #     dockerfile: console.Dockerfile
  #   image: my127/magento1-console:5.6-fpm-alpine
  #   depends_on:
  #     - php56-fpm-alpine-base

  php56-fpm-stretch-base:
    build:
      context: ./5.6/stretch/fpm
      dockerfile: base.Dockerfile
    image: my127/magento1:5.6-fpm-stretch

  php56-fpm-stretch-console:
    build:
      context: ./5.6/stretch/fpm
      dockerfile: console.Dockerfile
    image: my127/magento1-console:5.6-fpm-stretch
    depends_on:
      - php56-fpm-stretch-base

  # PHP 7.1

  # php71-fpm-alpine-base:
  #   build:
  #     context: ./7.1/alpine/fpm
  #     dockerfile: base.Dockerfile
  #   image: my127/magento1:7.1-fpm-alpine

  # php71-fpm-alpine-console:
  #   build:
  #     context: ./7.1/alpine/fpm
  #     dockerfile: console.Dockerfile
  #   image: my127/magento1-console:7.1-fpm-alpine
  #   depends_on:
  #     - php71-fpm-alpine-base

  php71-fpm-stretch-base:
    build:
      context: ./7.1/stretch/fpm
      dockerfile: base.Dockerfile
    image: my127/magento1:7.1-fpm-stretch

  php71-fpm-stretch-console:
    build:
      context: ./7.1/stretch/fpm
      dockerfile: console.Dockerfile
    image: my127/magento1-console:7.1-fpm-stretch
    depends_on:
      - php71-fpm-stretch-base

  # PHP 7.2

  # php72-fpm-alpine-base:
  #   build:
  #     context: ./7.2/alpine/fpm
  #     dockerfile: base.Dockerfile
  #   image: my127/magento1:7.2-fpm-alpine

  # php72-fpm-alpine-console:
  #   build:
  #     context: ./7.2/alpine/fpm
  #     dockerfile: console.Dockerfile
  #   image: my127/magento1-console:7.2-fpm-alpine
  #   depends_on:
  #     - php72-fpm-alpine-base

  php72-fpm-stretch-base:
    build:
      context: ./7.2/stretch/fpm
      dockerfile: base.Dockerfile
    image: my127/magento1:7.2-fpm-stretch

  php72-fpm-stretch-console:
    build:
      context: ./7.2/stretch/fpm
      dockerfile: console.Dockerfile
    image: my127/magento1-console:7.2-fpm-stretch
    depends_on:
      - php72-fpm-stretch-base
